- hosts: localhost
  vars:
  pre_tasks:
    - name: Update packages with dnf
      become: true
      dnf:
        name: '*'
        update_cache: true
        update_only: true
        state: latest
    - name: Remove packages not needed anymore
      become: true
      dnf:
        autoremove: true
  tasks:
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/dnf.yml
    - import_tasks: tasks/dotfiles.yml
