- name: Update packages with dnf
  become: true
  dnf:
    name: '*'
    update_cache: true
    update_only: true
    state: latest

- name: Remove packages not needed anymore
  become: true
  dnf:
    autoremove: true

- name: Install the 'Development tools' package group
  ansible.builtin.dnf:
    name: '@Development tools'
    state: present
  become: true
  tags: &tags_for_dnf_task ['dnf', 'install']

- name: Install ansible dependencies
  ansible.builtin.dnf:
    name:
      - autojump
      - autojump-zsh
      - code
      - stow
    state: present
  become: true
  tags: [*tags_for_dnf_task, 'ansible']

################################
# BEGIN: Programming languages #
################################

- name: Install Rust programming language (>=1.78) - also install cargo
  ansible.builtin.dnf:
    name:
      - rust >= 1.78
      - cargo >= 1.78
    state: present
  become: true
  tags: [*tags_for_dnf_task, 'rust', 'languages']

- name: Install Go programming language (>=1.22.3)
  ansible.builtin.dnf:
    name:
      - golang >= 1.22.3
    state: present
  become: true
  tags: [*tags_for_dnf_task, 'go', 'golang', 'languages']

################################
# END: Programming languages #
################################
